export default {
  ITEM_INFO: 'ITEM_INFO',
  POPULAR: 'POPULAR',
  RECOMMEND: 'RECOMMEND',
  REQUEST: 'REQUEST',
  NEW_ITEM: 'NEW_ITEM',
  ALL_ITEM: 'ALL_ITEM',
  REPAIR: 'REPAIR',
  GUEST_HISTORY: 'GUEST_HISTORY',
  CANCEL_REQUEST: 'CANCEL_REQUEST',
  ONLY_YOU: 'ONLY_YOU',
}